package com.github.lunchee.simplegraph

/**
 * A node of a Graph.
 *
 * Every Vertex of a Graph is distinguished from other Vertices by an ID of type [Int].
 * An ID is automatically generated by a Graph.
 *
 * A Vertex holds a user-defined data called Payload.
 */
class Vertex<out T>(
    val id: Int,
    val payload: T
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Vertex<*>
        return this.id == other.id
    }

    override fun hashCode(): Int {
        return id
    }

    override fun toString(): String {
        return "Vertex(id=$id)"
    }
}